name: 'OpenTofu'
on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  check-enabled:
    name: 'Check Enabled'
    runs-on: ubuntu-latest
    outputs:
      enabled: ${{ steps.check-project.outputs.enabled }}
    steps:
      - uses: actions/checkout@v3
      - uses: mikefarah/yq@v4.44.1
      - name: "Setup Env Variables"
        run:  |
          if [[ "${{github.event_name}}" != "pull_request" ]]; then
            echo "GIT_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
          fi
          if [[ "${{github.event_name}}" == "pull_request" ]]; then
            echo "GIT_BRANCH=$(echo ${GITHUB_BASE_REF} | tr / -)" >> $GITHUB_ENV
          fi
      - name: "Check Project Enabled"
        id: check-project
        run: |
          echo enabled=$(./run_tofu.sh -g project | yq -c "map(. == \"$GIT_BRANCH\") | any") >> $GITHUB_OUTPUT


  prepare-matrix:
    name: 'Prepare Matrix'
    runs-on: ubuntu-latest
    needs: check-enabled
    if: needs.check-enabled.outputs.enabled == 'true'
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: mikefarah/yq@v4.44.1
        name: "Set Matrix From Config"
        id: set-matrix
        run: echo "matrix=$(./run_tofu.sh -g modules | yq -c "map(.path)")" >> $GITHUB_OUTPUT

  tofu:
    name: 'OpenTofu'
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1

    - name: Setup YQ
      uses: mikefarah/yq@4.44.1

    - name: Define Environment Variables
      run: |
        if [[ "${{github.event_name}}" != "pull_request" ]]; then
          echo "GIT_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
        fi
        if [[ "${{github.event_name}}" == "pull_request" ]]; then
          echo "GIT_BRANCH=$(echo ${GITHUB_BASE_REF} | tr / -)" >> $GITHUB_ENV
        fi

    - name: Run Tofu
      id: run-tofu
      run: |
        if [[ "${{github.event_name}}" != "pull_request" ]]; then
          ./run_tofu.sh -p -m ${{ matrix.directory }} -k ${{ secrets.GCP_SA_KEY }}
        fi
        if [[ "${{github.event_name}}" == "pull_request" ]]; then
          ./run_tofu.sh -p -a -m ${{ matrix.directory }} -k ${{ secrets.GCP_SA_KEY }}
        fi

    - name: Comment PR
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `## Tofu Plan\n\`\`\`${{ steps.run-tofu.outputs.stdout }}\`\`\``;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `# Tofu Checks [${{ matrix.directory }}]\n**PR:** \`${{ github.head_ref }}\` **⇒** \`${{ env.GIT_BRANCH }}\`\n**Module:** \`${{ matrix.directory }}\`\n` + output
          })

